---
title: "Dev Documentation"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

```{r development-data}
# # Or use existing dataset
# my_dataset <- dplyr::starwars |>
#               dplyr::pull(species) |>
#               as.data.frame()
# #
# usethis::use_data(my_dataset, overwrite = TRUE)
#
# cat(sinew::makeOxygen("my_dataset"),file = here::here("R","doc_my_dataset.R") )
#
# rstudioapi::navigateToFile(here::here("R","doc_my_dataset.R"))
```


# get_info_data

```{r function-get_info_data}
#' Get info  on data
#'
#' allow to have information on a data set passed in parameter: dimensions and name of columns in a list
#'
#' @param data a data object
#'
#' @return a lit that contained the dimension and data object variable names
#'
#' @export
get_info_data <- function(data) {

  ## error management
  # data <- "1"
  # stopifnot(is.data.frame(data))
  if (!(is.data.frame(data))) stop("mydata is not a data frame")

  ## Get object dimension
  dimension <- dim(data)

  ## get object name
  names <- names(data)

  return(info = list(
    dimension = dimension,
    names = names
  ))
}
```

```{r example-get_info_data}
example <- get_info_data(data = iris)
# dput(example)
example

get_info_data(data = my_dataset)
```

```{r tests-get_info_data}
test_that("get_info_data works", {
  check <- get_info_data(data = iris)
  expect_true(inherits(get_info_data, "function"))
  expect_error(get_info_data(data = "1"), "mydata is not a data frame")
  expect_type(check, "list")
  expect_identical(
    check,
    list(
      dimension = c(150L, 5L),
      names = c(
        "Sepal.Length",
        "Sepal.Width",
        "Petal.Length",
        "Petal.Width",
        "Species"
      )
    )
  )
})
```

# get_mean_data

```{r function-get_mean_data}
#' get mean from data
#'
#' Get a table with the average of all numeric variables in your dataset as parameter.
#' (If the input table has no numeric variables, then the function must return an explicit message)
#' @param data a numeric vector
#' @return mean numeric value for the mean
#'
#' @export
get_mean_data <- function(data) {
  if (!is.numeric(data)) {
    stop("mydata is not a numeric")
  }
  result <- mean(data)
  return(result)
}
```

```{r example-get_mean_data}
test <- c(1, 2, 3)
get_mean_data(data = test)
```

```{r tests-get_mean_data}
test_that("get_mean_data works", {
  mymean <- get_mean_data(data = c(1, 2, 3))
  expect_true(inherits(get_mean_data, "function"))
  expect_error(get_mean_data(data = c("a")), "mydata is not a numeric")
  expect_type(mymean, "double")
  expect_identical(mymean, 2)
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Documentation", overwrite = TRUE)
```
