# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_mean_data works", {
  mymean <- get_mean_data(data =  c(1,2,3))
  expect_true(inherits(get_mean_data, "function")) 
  expect_error(get_mean_data(data = c("a")) , "mydata is not a numeric")
  expect_type( mymean, "double")
  expect_identical( mymean,2)
})
