# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_info_data works", {
  
  check <- get_info_data(data = iris)
  expect_true(inherits(get_info_data, "function")) 
  expect_error(get_info_data(data = "1"), "mydata is not a data frame")
  expect_type(check, "list")
  expect_identical(check,
                   list(
                     dimension = c(150L, 5L),
                     names = c(
                       "Sepal.Length",
                       "Sepal.Width",
                       "Petal.Length",
                       "Petal.Width",
                       "Species"
                     )
                   ))
})
