# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Get info  on data
#' 
#' allow to have information on a data set passed in parameter: dimensions and name of columns in a list
#' 
#' @param data a data object
#' 
#' @return a lit that contained the dimension and data object variable names
#' 
#' @export
#' @examples
#' example <- get_info_data(data = iris)
#' #dput(example)
#' example
#' 
#' get_info_data(data = my_dataset)
#' 
#' 
get_info_data <- function(data){
  
  ## error management
  # data <- "1"
  #stopifnot(is.data.frame(data))
  if(! (is.data.frame(data)) ) stop( "mydata is not a data frame")
  
  ## Get object dimension
  dimension = dim(data)
  
  ## get object name
  names = names(data)
  
  return ( info = list( dimension = dimension,
                        names = names))
    
}
